<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TENTANG</name>
   <tag></tag>
   <elementGuidId>02f9e2ab-c543-403e-be80-cdaf8163fd32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cca7c339-d16d-42ac-a326-8867f0f99d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#about</value>
      <webElementGuid>8c8df1d0-e96a-4fe8-b829-19a60583cbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TENTANG</value>
      <webElementGuid>f54be128-5546-40c7-9ff2-a7da1b35b104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;main-nav float-right d-none d-lg-block&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>5bad9e0e-2471-4ee7-b1a6-3ef2b86768b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/nav/ul/li[2]/a</value>
      <webElementGuid>89e6cd4d-0033-4709-ab96-fbe75eceb337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TENTANG')]</value>
      <webElementGuid>329be517-257f-42ca-81c7-8037668175d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::a[1]</value>
      <webElementGuid>2ab288b9-d04f-4559-98e4-f00ab1dcfdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FITUR'])[1]/preceding::a[1]</value>
      <webElementGuid>5694dbbd-a3ce-4577-9094-76cec7eb9723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KLIEN'])[1]/preceding::a[2]</value>
      <webElementGuid>37132a6d-dd6e-4b85-936d-5f8ac117a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TENTANG']/parent::*</value>
      <webElementGuid>da27d88f-2826-4414-bb08-e34fc19aef31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#about')]</value>
      <webElementGuid>54c20828-7251-4908-903b-bb1bfd28859d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>b0e5e3ac-e5f3-4099-ac5c-2110b5444dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#about' and (text() = 'TENTANG' or . = 'TENTANG')]</value>
      <webElementGuid>0472d1d8-9c8d-4335-8518-189b5a4210b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
