<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Point</name>
   <tag></tag>
   <elementGuidId>509e6bf6-f075-4e42-9ac4-3f95243bc4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>153c979d-bab6-47ce-ad57-335115413bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tablinks</value>
      <webElementGuid>4f9d369a-e55a-4b6e-980f-6c12932a8eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn5</value>
      <webElementGuid>d336f194-7a5d-4313-9609-ddcf895c2901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Point</value>
      <webElementGuid>de1a11f7-f02c-4aff-8942-6eca0cac9a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn5&quot;)</value>
      <webElementGuid>bb35b03c-6782-425c-825d-5e11fb14ed86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn5']</value>
      <webElementGuid>733f4096-99e1-4ca4-9ef2-3c904fb484da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/following::button[1]</value>
      <webElementGuid>eb8a55e3-8799-41bb-aa71-3bf5e39ab847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[1]/following::button[2]</value>
      <webElementGuid>368cbc5a-fe4c-4799-916f-d1c7ca188702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengapa portal pelanggan APL bernama eZRx?'])[1]/preceding::button[1]</value>
      <webElementGuid>f314afb2-3e7d-4fb4-b273-7c9e7e85fbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara mengakses eZRx?'])[1]/preceding::button[1]</value>
      <webElementGuid>5ec57505-79e3-4e99-aa8f-19d4f0d66bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Point']/parent::*</value>
      <webElementGuid>0047c676-5916-4c7d-a68d-2155a59ad878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>c3f3c7f2-6c41-4651-af77-466afd3ede78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn5' and (text() = 'Point' or . = 'Point')]</value>
      <webElementGuid>697a5c2a-d354-4456-ac49-1daca5f188b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
