<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ArtikelWaspada Hipoglikemia12 April 202_85d686</name>
   <tag></tag>
   <elementGuidId>6c49f0d4-ee06-40b5-99b9-0d03863e9dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua Informasi'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90eb53a4-ea6d-4eef-8274-785ed87f9226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>38156074-66dc-46a5-80f4-ed55181b9cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ArtikelWaspada Hipoglikemia12 April 2022 39 kali dilihat  Hipoglikemia atau gula darah rendah didefinisikan sebagai kondisi saat kadar gula (glukosa) darah kurang dari 70 mg/dL.  Selengkapnya Obat Kedaluwarsa, Apa yang Bisa Dilakukan?12 April 2022 24 kali dilihat  Tanggal kedaluwarsa obat menunjukkan jangka waktu dimana suatu obat tetap stabil, yang berarti obat tersebut tetap mempertahankan kekuatan, kualitas, dan kemurniannya jika disimpan sesuai kondisi yang tertera di label dan digunakan sebelum tanggal tersebut. Umumnya Selengkapnya Testing articel08 April 2022 19 kali dilihat  Testing articel Selengkapnya  Lihat Semua Artikel Rekanan APL3MHerbal RevivalActavis IndonesiaAmgen Manufacturing LimitedAtri DistribusindoAbbott Produk Indonesia Lihat Semua Rekanan Produk yang Sering Dibeli NATUR E HBL 100 ML Rp. 10.424Potensial program yang dapat digunakan : Tambah Ke Keranjang  SANGOBION VITATONIK 400ML Rp. 30.021Potensial program yang dapat digunakan : Tambah Ke Keranjang  Muat lebih banyak </value>
      <webElementGuid>9782f0f5-efea-4759-883f-16b80db26591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]</value>
      <webElementGuid>bddd8307-99e3-486f-8609-a9d499877e74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua Informasi'])[1]/following::div[1]</value>
      <webElementGuid>e069c106-4f2b-4975-bdcf-8942536f37e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[4]</value>
      <webElementGuid>2943797d-b2f4-477b-9ac0-5cbf23f08c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]</value>
      <webElementGuid>b6a1effc-8b02-4951-8157-dd875f7d94e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ArtikelWaspada Hipoglikemia12 April 2022 39 kali dilihat  Hipoglikemia atau gula darah rendah didefinisikan sebagai kondisi saat kadar gula (glukosa) darah kurang dari 70 mg/dL.  Selengkapnya Obat Kedaluwarsa, Apa yang Bisa Dilakukan?12 April 2022 24 kali dilihat  Tanggal kedaluwarsa obat menunjukkan jangka waktu dimana suatu obat tetap stabil, yang berarti obat tersebut tetap mempertahankan kekuatan, kualitas, dan kemurniannya jika disimpan sesuai kondisi yang tertera di label dan digunakan sebelum tanggal tersebut. Umumnya Selengkapnya Testing articel08 April 2022 19 kali dilihat  Testing articel Selengkapnya  Lihat Semua Artikel Rekanan APL3MHerbal RevivalActavis IndonesiaAmgen Manufacturing LimitedAtri DistribusindoAbbott Produk Indonesia Lihat Semua Rekanan Produk yang Sering Dibeli NATUR E HBL 100 ML Rp. 10.424Potensial program yang dapat digunakan : Tambah Ke Keranjang  SANGOBION VITATONIK 400ML Rp. 30.021Potensial program yang dapat digunakan : Tambah Ke Keranjang  Muat lebih banyak ' or . = 'ArtikelWaspada Hipoglikemia12 April 2022 39 kali dilihat  Hipoglikemia atau gula darah rendah didefinisikan sebagai kondisi saat kadar gula (glukosa) darah kurang dari 70 mg/dL.  Selengkapnya Obat Kedaluwarsa, Apa yang Bisa Dilakukan?12 April 2022 24 kali dilihat  Tanggal kedaluwarsa obat menunjukkan jangka waktu dimana suatu obat tetap stabil, yang berarti obat tersebut tetap mempertahankan kekuatan, kualitas, dan kemurniannya jika disimpan sesuai kondisi yang tertera di label dan digunakan sebelum tanggal tersebut. Umumnya Selengkapnya Testing articel08 April 2022 19 kali dilihat  Testing articel Selengkapnya  Lihat Semua Artikel Rekanan APL3MHerbal RevivalActavis IndonesiaAmgen Manufacturing LimitedAtri DistribusindoAbbott Produk Indonesia Lihat Semua Rekanan Produk yang Sering Dibeli NATUR E HBL 100 ML Rp. 10.424Potensial program yang dapat digunakan : Tambah Ke Keranjang  SANGOBION VITATONIK 400ML Rp. 30.021Potensial program yang dapat digunakan : Tambah Ke Keranjang  Muat lebih banyak ')]</value>
      <webElementGuid>92793871-5a47-4187-b783-0bb0a8915dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
