<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BerhasilProduk berhasil dihapus dari keranjang</name>
   <tag></tag>
   <elementGuidId>d5ad350a-ab12-4f59-bec4-00c47d6d9c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alert-modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alert-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fd9d7e1-d40e-4529-83a2-a61a2a72b6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>exampleModalCenterTitle</value>
      <webElementGuid>7e69e6a4-79b5-4bde-925f-ce58d23b993e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal fade show</value>
      <webElementGuid>82e693cc-aa36-4246-9204-c716d26f8635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>5fa02ed2-9e58-45d7-b6a4-430162955685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c5f2a459-fc47-40e6-9331-2b04cb9d3f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-modal</value>
      <webElementGuid>7860daba-430b-4eb4-a848-e03c952e704a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20a9a1a0-62b8-4243-99d4-e81d5b139c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BerhasilProduk berhasil dihapus dari keranjang</value>
      <webElementGuid>027c1f90-09fe-4813-bfe3-bd6c5364bdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-modal&quot;)</value>
      <webElementGuid>388abbf4-4917-4167-9d90-31dffbd2067c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='alert-modal']</value>
      <webElementGuid>076789ce-934d-4f6f-95d5-627a8a6d2ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAMBAH PRODUK LAIN'])[1]/following::div[1]</value>
      <webElementGuid>42e51d6b-2633-4f27-bc79-36460ec10d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPDATE KERANJANG'])[1]/following::div[2]</value>
      <webElementGuid>34ca6fcb-59f5-4381-ac2c-d08975edc73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='undefined'])[1]/preceding::div[6]</value>
      <webElementGuid>e11f93d9-7f2b-493c-81d4-9219f351bd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-alert/div</value>
      <webElementGuid>b34b96cb-5436-4bd5-becc-a6444cc73f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'alert-modal' and (text() = 'BerhasilProduk berhasil dihapus dari keranjang' or . = 'BerhasilProduk berhasil dihapus dari keranjang')]</value>
      <webElementGuid>46790e2e-5b91-4fd8-86a7-0720294866d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
