<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Produk gagal ditambahkanMaaf, stok prod_142143</name>
   <tag></tag>
   <elementGuidId>f3bb3101-af99-4283-b696-bd0fe397b645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-product-success-added']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-product-success-added</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f1307c1c-2110-466e-9908-faa7d5f0a0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>exampleModalCenterTitle</value>
      <webElementGuid>db499c6f-2e81-4cca-a0e4-27d998f1c656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal fade show</value>
      <webElementGuid>07d9c521-0702-43eb-8ca6-d663d165db41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>4916819e-980a-4df9-93db-8b454a4b7313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e2d61a11-872f-4b82-9908-c639618a4ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-product-success-added</value>
      <webElementGuid>2e0a05bf-6d30-4d10-ae4b-da70453137ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e685e10-aef6-4a28-8214-d1c0de352ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Produk gagal ditambahkanMaaf, stok produk kosongARCH PROBE ZALKRp. 3.912.000Estimasi Ketersediaan : 0 KITED (Expiry Date) : -QTY : 2Total Pesanan : Rp. 7.824.000Lihat KeranjangTambah Produk Lain</value>
      <webElementGuid>4aece52d-4f68-4cd6-845d-dade44ee337c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-product-success-added&quot;)</value>
      <webElementGuid>d57a99e9-8f75-4ed2-8473-14d3afdb503b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='modal-product-success-added']</value>
      <webElementGuid>142901ae-3876-4497-b7b6-1dbb5d1d2247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/following::div[1]</value>
      <webElementGuid>9a201d8d-7a40-4ca9-aeb3-e10e2ca11851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMPAN'])[1]/following::div[1]</value>
      <webElementGuid>4fcdc775-2b98-4ac5-8eb2-57a8576b541f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-product-success-add/div</value>
      <webElementGuid>06d4079c-62c2-4810-b07d-37f962dad3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'modal-product-success-added' and (text() = '×Produk gagal ditambahkanMaaf, stok produk kosongARCH PROBE ZALKRp. 3.912.000Estimasi Ketersediaan : 0 KITED (Expiry Date) : -QTY : 2Total Pesanan : Rp. 7.824.000Lihat KeranjangTambah Produk Lain' or . = '×Produk gagal ditambahkanMaaf, stok produk kosongARCH PROBE ZALKRp. 3.912.000Estimasi Ketersediaan : 0 KITED (Expiry Date) : -QTY : 2Total Pesanan : Rp. 7.824.000Lihat KeranjangTambah Produk Lain')]</value>
      <webElementGuid>6ef52419-064f-46c3-867d-d693f30e1da4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
