<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_APL CUSTOMER PORTAL_form-group has-form2</name>
   <tag></tag>
   <elementGuidId>00a1c47a-bce8-4489-97be-ada437153b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-login']/div/div/div[2]/div/form/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.has-form2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3df5a2c-3f7e-4a7a-82d5-2934478e1a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group has-form2</value>
      <webElementGuid>b24100e8-89fd-4155-8140-0aca056c43cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-login&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;login-page ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;form-group has-form2&quot;]</value>
      <webElementGuid>b21eed51-2cfd-4633-ae65-3f21b206e82c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-login']/div/div/div[2]/div/form/div</value>
      <webElementGuid>a4e3c115-e168-4ba4-b6c7-9cc963ba359b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APL CUSTOMER PORTAL'])[3]/following::div[1]</value>
      <webElementGuid>cf31ead0-abc3-4de9-b9bc-f288632bb7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MASUK'])[2]/following::div[1]</value>
      <webElementGuid>8e83a2da-510e-4fe6-ab5d-da511f24b1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/preceding::div[3]</value>
      <webElementGuid>494e9a19-ead8-4b56-82a4-558a32b95f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingat Saya (Opsional)'])[1]/preceding::div[4]</value>
      <webElementGuid>74c4b3d0-07d4-4df9-9cf3-bad532672a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>985e079e-8daf-46e8-ad5a-602ef64af1da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
