<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Talk to Us</name>
   <tag></tag>
   <elementGuidId>00c02147-9ef9-462a-aad8-079ca064e80e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Qiscus'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.qcw-trigger-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10f1e5c9-3872-4000-8361-1e21c7d1b82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qcw-trigger-btn</value>
      <webElementGuid>8c0d7515-399c-4a1b-8be2-d44ceeb439aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Talk to Us</value>
      <webElementGuid>8a7329b3-1da0-4a10-b776-d6dd33f101eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;qcw-container qcw-container--open&quot;]/div[@class=&quot;qcw-trigger-btn&quot;]</value>
      <webElementGuid>4972160e-a757-4197-9e4f-8e08f8cc2353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3efda1e7-67c1-4d1a-a443-1fd1a231a8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Talk to Us</value>
      <webElementGuid>4b1819d4-43b5-4ff5-b635-e870b5bc0c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;qcw-container qcw-container--open&quot;]/div[@class=&quot;qcw-trigger-btn&quot;]/div[1]</value>
      <webElementGuid>0842b1dd-bb3e-437a-a4e4-673293f80385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5532c7e-300f-403e-bc85-8822c7cd8e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Talk to Us</value>
      <webElementGuid>a6220b2f-00d4-405e-a11d-2b2d72c13d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;qcw-container qcw-container--open&quot;]/div[@class=&quot;qcw-trigger-btn&quot;]/div[1]</value>
      <webElementGuid>ace15a8e-d612-4fde-9288-e02a9f7d341d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca8e155d-754f-4771-beb1-53a0abc24310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qcw-trigger-btn</value>
      <webElementGuid>f1ae99e2-ab57-4d20-b2e0-ee2d3297be3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Talk to Us</value>
      <webElementGuid>95926548-e4f6-4b0b-9763-01b88dc4485b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;qcw-container qcw-container--open&quot;]/div[@class=&quot;qcw-trigger-btn&quot;]</value>
      <webElementGuid>02b5d5bf-21d7-4629-a69a-f2f168c07e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qiscus'])[1]/following::div[1]</value>
      <webElementGuid>00c079db-22f0-4fcf-a53b-91c006612004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>bac64c97-6582-4570-9b4d-95e86efcda38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Talk to Us' or . = 'Talk to Us')]</value>
      <webElementGuid>172f7e7e-88c3-4929-adfc-1010e057bb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qiscus'])[1]/following::div[2]</value>
      <webElementGuid>f9232af4-2265-47d6-9e1b-69155e90d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Talk to Us']/parent::*</value>
      <webElementGuid>21e943d9-ab28-4176-a7d2-657104b4fc6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>fd6635cb-f845-4d24-9b33-83363d531a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
