<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_APL CUSTOMER PORTAL_fa fa-eye</name>
   <tag></tag>
   <elementGuidId>0cf1720c-e92e-4539-a4a4-0e53e662530e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-login']/div/div/div[2]/div/form/div[2]/div/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-eye</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bad7ccdf-9472-494c-84a5-49d4d0762920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>cb07b2c1-de56-4228-8d9b-4c4ed8d9abf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-login&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;login-page ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-group has-form2&quot;]/div[@class=&quot;row&quot;]/span[@class=&quot;fa form-control-feedback&quot;]/i[@class=&quot;fa fa-eye&quot;]</value>
      <webElementGuid>8b38b92e-1600-41d2-ae68-a29dd0220c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-login']/div/div/div[2]/div/form/div[2]/div/span[2]/i</value>
      <webElementGuid>b55e754c-fa4c-4468-ab8f-7e8fa58914c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>ac5baa9c-e957-4ae3-a19c-5675b536cb37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
