<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bantuan_img-fluid</name>
   <tag></tag>
   <elementGuidId>28b55c95-3234-4bf4-b209-449345cfd1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d8f483e5-5a89-4d48-ae69-bd0b17a0cb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>bd0fafd3-25c1-41f6-aaa0-235e7e4e6c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/asset-landing-page/img/landing-page/14.png</value>
      <webElementGuid>f12be917-ef33-40e7-ab3f-deddd401815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-list-cart[1]/div[@class=&quot;wrapper&quot;]/app-admin-header[1]/div[@class=&quot;main-header&quot;]/div[@class=&quot;logo-header&quot;]/a[@class=&quot;logo&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>10692cea-6d27-4bc7-ab93-3ac9f2fa22e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9077d57-73ec-4c06-a212-9cc756279eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>3083673d-65ad-4457-82da-c9a2dd892295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/asset-landing-page/img/landing-page/14.png</value>
      <webElementGuid>3b96b472-33b1-4ed7-a4ff-7decbcfde50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-list-cart[1]/div[@class=&quot;wrapper&quot;]/app-admin-header[1]/div[@class=&quot;main-header&quot;]/div[@class=&quot;logo-header&quot;]/a[@class=&quot;logo&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>fd3a9050-56db-4c67-9e2c-27b11c38da25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f32a2e2e-cdb1-455c-a480-720594f8f4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/asset-landing-page/img/landing-page/14.png']</value>
      <webElementGuid>24ce78d0-3430-4a4f-a4fa-d893f2d73872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
