<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_dropdown-multiselect__caret</name>
   <tag></tag>
   <elementGuidId>4199199f-fbe5-4094-823c-f51184cff0a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dropdown-multiselect__caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7fbc2960-5fc1-415a-917c-8c6457fe19fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-multiselect__caret</value>
      <webElementGuid>c99ce7b7-2919-4ea4-b635-f02ab650d489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-list-product[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sidebar sidebar-white&quot;]/app-search-filter[1]/div[@class=&quot;sidebar-wrapper&quot;]/div[1]/div[@class=&quot;input-group&quot;]/ng-multiselect-dropdown[@class=&quot;custom-select my-select ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/div[1]/span[@class=&quot;dropdown-btn&quot;]/span[2]/span[@class=&quot;dropdown-multiselect__caret&quot;]</value>
      <webElementGuid>2930f089-eba2-4278-b65c-0a77622ea1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee020675-7bd0-4242-a244-f4e90d4e01c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-multiselect__caret</value>
      <webElementGuid>eecfce9c-e542-494b-a676-d653754b963d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-list-product[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sidebar sidebar-white&quot;]/app-search-filter[1]/div[@class=&quot;sidebar-wrapper&quot;]/div[1]/div[@class=&quot;input-group&quot;]/ng-multiselect-dropdown[@class=&quot;custom-select my-select ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/div[1]/span[@class=&quot;dropdown-btn&quot;]/span[2]/span[@class=&quot;dropdown-multiselect__caret&quot;]</value>
      <webElementGuid>d2b6c418-3cca-44f8-b36c-c1a7eb4164d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a24824d2-595b-4a02-ba60-49c809600812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-multiselect__caret</value>
      <webElementGuid>4ee86589-c57c-42a4-95f1-19175d494594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-list-product[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sidebar sidebar-white&quot;]/app-search-filter[1]/div[@class=&quot;sidebar-wrapper&quot;]/div[1]/div[@class=&quot;input-group&quot;]/ng-multiselect-dropdown[@class=&quot;custom-select my-select ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/div[1]/span[@class=&quot;dropdown-btn&quot;]/span[2]/span[@class=&quot;dropdown-multiselect__caret&quot;]</value>
      <webElementGuid>0372a318-75ab-469e-a6e7-8010879677ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63beec01-ae34-4891-8d8e-53c66c9c7b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-multiselect__caret</value>
      <webElementGuid>aa52e53b-a1b2-41f1-9c92-4af7c9ebb5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-list-product[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sidebar sidebar-white&quot;]/app-search-filter[1]/div[@class=&quot;sidebar-wrapper&quot;]/div[1]/div[@class=&quot;input-group&quot;]/ng-multiselect-dropdown[@class=&quot;custom-select my-select ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/div[1]/span[@class=&quot;dropdown-btn&quot;]/span[2]/span[@class=&quot;dropdown-multiselect__caret&quot;]</value>
      <webElementGuid>0fd26fa7-7804-47d6-aa8f-68c7cabde0cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>bc06d4e0-6def-4fd3-9f75-5d652c5afc23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
