<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add (1)</name>
   <tag></tag>
   <elementGuidId>4c951009-6273-41b1-9a72-342621ee5d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-padd2.green.margin-right-10.margin-bottom-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;Utility.LoadMenu('/CMS/Product/Create')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e6f5698-964e-4ea2-9393-49cef1e61f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b2e8bab4-d379-4801-ae8f-5d540daeeebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/Product/Create')</value>
      <webElementGuid>53db6a8e-654d-4d62-8f0b-ebbd87215872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>76c08b32-28d9-4ba3-8f42-5476f86a3807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Add</value>
      <webElementGuid>13bfb90f-ce6a-4742-9935-6433d48951ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;render-body&quot;)/div[@class=&quot;portlet light shadow&quot;]/div[@class=&quot;portlet-title&quot;]/div[@class=&quot;btn-act-list&quot;]/a[@class=&quot;btn btn-padd2 green margin-right-10 margin-bottom-10&quot;]</value>
      <webElementGuid>2bcdc15b-4b19-4f44-a6bd-aba04f6bb9c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;Utility.LoadMenu('/CMS/Product/Create')&quot;]</value>
      <webElementGuid>99b63bcf-4931-4de9-859d-f2f62adbe04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='render-body']/div[3]/div/div/a</value>
      <webElementGuid>c9e0ae15-1c4d-4225-915b-d54f27b5896d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add')]</value>
      <webElementGuid>0d14027a-0404-4bd3-8cfe-cf8cce604623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Product'])[1]/following::a[3]</value>
      <webElementGuid>6d2878fe-8064-4374-9c49-b258b0a2c6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Product'])[1]/following::a[5]</value>
      <webElementGuid>97ecb88b-0471-477a-a1ef-524c9eed62f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[66]</value>
      <webElementGuid>32a327cb-2e52-4be4-8027-8d9a1e7002b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/a</value>
      <webElementGuid>f242ada4-7cff-4210-82f7-2d5c7636d37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '   Add' or . = '   Add')]</value>
      <webElementGuid>8fc91b75-d417-434e-bfff-e7c93a2a1d8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
