<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>01343816-12c6-455a-bfc1-7ae089fb55ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;Utility.LoadMenu('/CMS/Home/Dashboard/')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dashboard > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb3b6b27-97c9-4f98-b596-e79bd934b860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c0f3c69f-0e2e-47cc-8cb9-d629d50a793c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/Home/Dashboard/')</value>
      <webElementGuid>0d7c1499-1678-470e-9e1d-a59d996a3420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Dashboard </value>
      <webElementGuid>4b82ccab-db1c-42bb-a9cb-8b041d538cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dashboard&quot;)/a[1]</value>
      <webElementGuid>a5eb747b-1387-4bdb-8f36-b8aaa1e77f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;Utility.LoadMenu('/CMS/Home/Dashboard/')&quot;]</value>
      <webElementGuid>45ce15f1-6bd7-4ee0-8b3b-841879a2064a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Dashboard']/a</value>
      <webElementGuid>4c2eb9cb-22e1-4036-93c4-e5949195b0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SADM'])[1]/following::a[3]</value>
      <webElementGuid>103b1e81-0208-42f4-861e-e72b8b035623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/preceding::a[1]</value>
      <webElementGuid>70b83c56-414d-4df0-add8-9e059c814854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>60b74365-00b2-4637-9164-01586d5471a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/ul/li/a</value>
      <webElementGuid>a5feda2f-5bb2-4a30-ab48-7f70ad7b0996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '  Dashboard ' or . = '  Dashboard ')]</value>
      <webElementGuid>f4c39044-9a91-4ade-83bc-f7aa7221201d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
