<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download Template</name>
   <tag></tag>
   <elementGuidId>3deabec8-8a0b-4cb1-9fff-5e1b5c89e491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='render-body']/div[3]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>987bd699-aacc-4227-b0ba-d923fc76ea6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CMS/Product/DownloadTemplate</value>
      <webElementGuid>18424b5d-e33a-4286-9dfa-e87af11b06e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>3bd00815-3086-4fcd-ad12-8dda46f37c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Download Template</value>
      <webElementGuid>0e778fb6-8a25-41ca-b335-4d98c602082a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;render-body&quot;)/div[@class=&quot;portlet light shadow&quot;]/div[@class=&quot;portlet-title&quot;]/div[@class=&quot;btn-act-list&quot;]/a[@class=&quot;btn btn-padd2 green margin-right-10 margin-bottom-10&quot;]</value>
      <webElementGuid>c30495e1-6990-48ec-bcaf-c0e2f1d7929a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb03cf7c-f506-4b64-abaa-4831c046d542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CMS/Principal/DownloadTemplate</value>
      <webElementGuid>2d916395-3e71-440b-a2e7-29600870527f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>81ffe42c-d1d7-460a-8e3d-1479e717839b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Download Template</value>
      <webElementGuid>638ab439-b5e7-4cd3-a245-adf54e15138d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;render-body&quot;)/div[@class=&quot;portlet light shadow&quot;]/div[@class=&quot;portlet-title&quot;]/div[@class=&quot;btn-act-list&quot;]/a[@class=&quot;btn btn-padd2 green margin-right-10 margin-bottom-10&quot;]</value>
      <webElementGuid>73c2cf6f-089a-4f67-a65a-4f404c337c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea26acba-5110-4167-bdf9-3c32eb0adf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CMS/Principal/DownloadTemplate</value>
      <webElementGuid>b33d81a1-e8e4-40c9-a708-306844acbfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>84026cc1-192a-48c1-9d0f-a17a3b3e370e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Download Template</value>
      <webElementGuid>5e4c360b-4399-4a0f-8417-64c2ef5ba656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;render-body&quot;)/div[@class=&quot;portlet light shadow&quot;]/div[@class=&quot;portlet-title&quot;]/div[@class=&quot;btn-act-list&quot;]/a[@class=&quot;btn btn-padd2 green margin-right-10 margin-bottom-10&quot;]</value>
      <webElementGuid>e5a258e4-4410-432e-ac1d-a75cc2c19108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc2dcf7a-8485-4e4c-b3cb-cbbafa243157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CMS/Product/DownloadTemplate</value>
      <webElementGuid>b6515614-bc5f-4b9f-bf14-22bcaa0fbbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>3fb509d7-8cab-4e13-a23b-564642010858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Download Template</value>
      <webElementGuid>47fb127b-a904-4071-a606-3cd8715ae2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;render-body&quot;)/div[@class=&quot;portlet light shadow&quot;]/div[@class=&quot;portlet-title&quot;]/div[@class=&quot;btn-act-list&quot;]/a[@class=&quot;btn btn-padd2 green margin-right-10 margin-bottom-10&quot;]</value>
      <webElementGuid>24d0e2fd-ffaa-4e3a-97ac-0a27d26648d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='render-body']/div[3]/div/div/a[2]</value>
      <webElementGuid>88da6102-af20-4d96-9e16-471cf9b62828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download Template')]</value>
      <webElementGuid>6069212b-74db-4a9f-993d-7dc5d70e7f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Product'])[1]/following::a[4]</value>
      <webElementGuid>0465e515-f91a-461c-99b8-47ea175bc0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::a[1]</value>
      <webElementGuid>3abec97f-8932-4f6e-a0c4-ff7b0ba7d522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CMS/Product/DownloadTemplate')]</value>
      <webElementGuid>6819fc67-d90f-4750-b788-c6431cafcf02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>18bbf5b7-80b5-493e-a567-402087c31f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/CMS/Product/DownloadTemplate' and (text() = '  Download Template' or . = '  Download Template')]</value>
      <webElementGuid>8434310d-a210-4d2f-9076-50d3eab1ea1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='render-body']/div[3]/div/div/a[3]</value>
      <webElementGuid>aafba6a4-d0cc-4131-8c45-57eb27f3841f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Principal'])[1]/following::a[5]</value>
      <webElementGuid>8bbfc3d9-aa1c-4d95-84b8-8a7882ec5e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Principal'])[1]/following::a[7]</value>
      <webElementGuid>171fdd22-d228-4c7d-8a68-ebb6fe4b8595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::a[1]</value>
      <webElementGuid>2f2402d4-2610-4847-80dc-16d63f1739fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CMS/Principal/DownloadTemplate')]</value>
      <webElementGuid>3a73cc5d-9ba7-4057-87e6-beaa1d588062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>e2afcbc9-806a-4780-b396-622cfd4c8bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/CMS/Principal/DownloadTemplate' and (text() = '  Download Template' or . = '  Download Template')]</value>
      <webElementGuid>d54d7578-ea31-4a1c-8b59-3eb370cb22f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
