<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Product_1 (1)</name>
   <tag></tag>
   <elementGuidId>5724abe6-6839-4091-8a28-70703a0b2f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Product > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;Utility.LoadMenu('/CMS/Product/')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>474e0c93-fe14-460a-9171-30804890787e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b004620a-abc5-409f-a35c-e06cf94cb4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/Product/')</value>
      <webElementGuid>b849097f-0836-41d4-ac2c-d8a792841761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product</value>
      <webElementGuid>9a7afb75-c013-4d68-a527-8426ed1b3440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Product&quot;)/a[1]</value>
      <webElementGuid>5b905c5d-d59b-4098-b5f9-1a3f6af5f99c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;Utility.LoadMenu('/CMS/Product/')&quot;]</value>
      <webElementGuid>9f99ec02-3758-4b72-9a6d-3dfcf6267cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Product']/a</value>
      <webElementGuid>d91f73aa-0c7b-49e1-94a5-3745719dc172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Product')]</value>
      <webElementGuid>1e832838-16a8-4b3b-840b-4750a8ab6829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::a[1]</value>
      <webElementGuid>c76d75c7-5796-47ab-99a8-ac5e640be7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::a[13]</value>
      <webElementGuid>f2016917-04ef-4a62-91c2-7eceb01c0a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/preceding::a[1]</value>
      <webElementGuid>89970108-4b9f-45a7-a541-ae6947191e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::a[9]</value>
      <webElementGuid>3587a9ce-16b6-456b-84e6-d387566d00da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>20058d2f-bc0b-4206-a25a-5a590a4782d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/a</value>
      <webElementGuid>869bbf2d-9bb3-41d9-866d-97fb536461c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Product' or . = 'Product')]</value>
      <webElementGuid>b727ee5e-4ff5-495e-92fe-4673f704e256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
