<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ED Settings</name>
   <tag></tag>
   <elementGuidId>ac402cf2-4f95-4d76-8e2b-0b322c03c586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnEDSetting']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnEDSetting</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce8681fd-f3b5-467c-a99c-d884e4016310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ef5ffd2-7ac2-4f3f-ae6b-2ab5133e38d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>72ce6d3c-491c-4d5f-93ad-7a8bea3111a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>a82a8263-1c1e-4b3e-a471-9114a8f347b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>56c58355-4b05-4867-964e-1b67c4c0d9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>d704a064-761d-4d3c-b42b-3328c3bc9e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>98f5c82f-45ca-444d-b0a5-23a3f49744a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71265325-a20c-44f9-b383-3b82aa0bd127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e149d471-db18-4e1f-8093-7f8c01c7c32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>7181dc69-dc2a-4d08-8074-188b5f7ee9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>08bde392-09ee-4b92-8fb1-3c01fb1e84c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>a7778a01-b205-4d5f-8780-c8b6a7ed4fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>10616d38-566d-463e-af00-04d1c5330e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>60b294c0-a167-447a-987a-55ccf0d40caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61ab98a4-1477-4e48-8ef5-4defe8eb519a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f171c01e-ab2b-4fd3-9ce7-9c60cae544ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>5b558548-9cdc-4de6-95c5-5189f93a5e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>722e545a-d977-48c8-870f-896706b7623a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>aa7982ec-a979-4123-875d-a4b1c3a65420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>e1f79b6f-6d52-48a8-b540-bc3e5eef7052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>aec76c06-ca1f-49c7-b99a-6349c545ab1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2bb2718-9c97-47d2-863a-c38b9970c20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6fdedf0-ad91-4fbe-bbfc-7a9f12abb337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>a96c3824-97b5-4678-ad4f-5e1380d7de46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>dcf67cf2-0bdf-4e38-8224-d475b39bc65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>a43505e8-6744-4374-8c83-f9c22d16dd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>c30879e4-5161-4cee-ac31-844b475f60be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>93ccaa51-8e57-4f29-93a7-f4f28436bb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9d91a94-30a6-44b1-83de-817e31f6a943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>300d57c7-757d-4a51-8824-3910e987f9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>1dad0070-5c1a-4eb4-9568-2c24520242f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>3ecc7535-2e19-4912-a05b-2a1670113c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>7ac13398-5064-4c28-a53b-9323d72e3572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>8853b511-89cb-4370-a754-ae796783d0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>319b4b52-286d-4562-8649-52bea31e2bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c142b27e-5cfb-404e-aa1e-76588ced9857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3346fd74-33e3-485d-9caf-676219bb0640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>3c334a48-dd02-4be7-88c1-bfea7e5d0ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>e2d53791-465e-42c6-9f28-2163b8d75de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>7db8f257-650d-4e9e-8bff-5c08f23da520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>868732a2-840b-4e6d-aca7-7018a539480c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>f9f74bb0-bfce-4cde-a065-2aff3123b026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27da96f0-afe1-4b8b-9baa-2f109093292a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6bd454f-337d-47de-8b26-756e9863fde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>f3d997bc-7548-43be-bd77-e460fbb2e026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>12041186-2d0b-41cb-ad8a-da3e744fb5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>cd9a4e54-0f6f-4047-a415-8deb0ee50710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>e8535ddf-e613-4e99-ae05-a1498e9101d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>eb241bfc-2f38-4d3b-b82b-3b4f7a3aaa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c4e2146-18f8-4da7-b64e-4336323eea9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db239d3d-76a8-4601-ab9a-a522cf96de2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>78f87276-4ef9-4c3d-97f2-b1f6403df40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>336d876e-b863-4ae5-a91e-208959143643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>9b0ab89e-0e7f-48c2-aebe-f58176727135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>d4b1602f-1e68-4fc9-99fe-a8838b8979e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>dc803779-a322-414a-9617-c6fdde30bdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7b3cc5d-0402-429d-8f5c-2a1a393164e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e25bf09-d35f-40ea-b8a9-a29d80c6ad60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>b0ee078f-ccd2-418c-971b-15baca51e50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>6e422a50-bbc4-4af3-b9b9-bd333f3246c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>6b8c0c6f-6e76-46e2-b5a9-4bb5cc5756df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>76df9719-62c7-4f85-957d-8720a9e54831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>eda12d01-d75c-4aa1-93a8-bb5e6678c0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5052ef2f-385f-4c76-9e3f-a5ae3fa11b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c3a5986-75fc-4c17-bc52-2a0c011100cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>22e5499e-2f2c-470c-88a0-5c1f64d3da38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>20d60852-859a-427b-8ad0-2980c87caab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>7e3ddf22-b10f-4051-a97f-ec34c05174a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>e5164e0c-7851-4f09-81e4-96db53aada45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>fb95b8c3-839a-4632-8ea7-2664a3065bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfbf5e7c-f5d3-43e1-bc09-1ca3aefc0674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bba91bf-5f5f-4719-acd4-2413280ca622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>6632e23f-9695-4cc6-9a9a-7c56eea86b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEDSetting</value>
      <webElementGuid>2801f28d-792c-4f73-8f1c-ceed92db6d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utility.LoadMenu('/CMS/EDSetting/Set/')</value>
      <webElementGuid>e03e2fec-fccf-44fc-a162-e9f5f778b355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ED Settings</value>
      <webElementGuid>7dea5972-8722-43e5-a88e-b7ad08198074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEDSetting&quot;)</value>
      <webElementGuid>8d07dfa6-feeb-44f0-a8d6-c07ec481f398</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnEDSetting']</value>
      <webElementGuid>5e18cfad-c16e-4c82-a164-9eca3d8ebf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='render-body']/div[2]/div/div/div/button[2]</value>
      <webElementGuid>71002fe8-1590-406c-8531-e0414db9383b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ED Setting'])[2]/following::button[2]</value>
      <webElementGuid>078075ae-bb21-4cf4-b511-c74931540464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal'])[3]/preceding::button[2]</value>
      <webElementGuid>2684d33f-2aff-4730-b3b2-ea0be3a684ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Principal'])[1]/preceding::button[2]</value>
      <webElementGuid>f1fc4afa-fd4a-467c-9efa-1b433c6087e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ED Settings']/parent::*</value>
      <webElementGuid>a04d1457-d715-4ee2-8268-de0019ce01c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>dcc462c6-d16d-4131-8aad-c13d205ce530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnEDSetting' and (text() = 'ED Settings' or . = 'ED Settings')]</value>
      <webElementGuid>b84be775-d0dc-46b6-b78a-3ae8da47035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABI - Abbott'])[1]/preceding::button[2]</value>
      <webElementGuid>4e3e1639-eb69-4c7c-860d-3262e732410c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
