<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export Data</name>
   <tag></tag>
   <elementGuidId>27fc5646-a8a6-4b29-a9bc-182455daf519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-export']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-export</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d1dc89c-73f7-4f1d-998c-4cdee1b0d51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbdab42f-de80-4d16-9926-45c5000e9f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd2 green margin-right-10 margin-bottom-10</value>
      <webElementGuid>a9b0ff31-845a-4aff-9b65-6616033b153d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-export</value>
      <webElementGuid>c6cb3550-dad9-4fd0-8df8-fbef107df1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Export Data</value>
      <webElementGuid>af7498b3-a893-404f-bff4-5b3aafcbdbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-export&quot;)</value>
      <webElementGuid>899e4dcc-a209-4aea-8ad1-b063e741799f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-export']</value>
      <webElementGuid>17d4d286-c4dd-45fe-88c3-79e2861ca1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='render-body']/div[2]/div/div/div/button</value>
      <webElementGuid>cf21f2d5-8e7f-4371-b98d-89e03675e642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ED Setting'])[2]/following::button[1]</value>
      <webElementGuid>209d095e-285e-4b88-a102-ffb98c28a671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Register'])[1]/following::button[1]</value>
      <webElementGuid>20bfe6e2-5ac5-40e6-9897-0cdc2420da74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ED Settings'])[1]/preceding::button[1]</value>
      <webElementGuid>015f7798-0e83-4969-9272-1401cd6d7516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal'])[3]/preceding::button[3]</value>
      <webElementGuid>2bb716cc-15ce-44f2-8036-de9cff44f65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7fba5357-b9ef-4d29-b3aa-ad709b3647a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-export' and (text() = '  Export Data' or . = '  Export Data')]</value>
      <webElementGuid>5dd305b8-031e-49db-89d6-b118cdc16250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
