<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Saatinianda terdaftar sebagai Customer _4297be</name>
   <tag></tag>
   <elementGuidId>b9610c0b-ff07-4b7a-9da3-4ba83ca0f20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.note-editable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='FormEditTemplate']/div/div/div[3]/div/div/div/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b9a5d87-3014-4273-94a6-407861361032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editable</value>
      <webElementGuid>acd7b817-93f9-4aca-9db3-3af6c74eb62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f9e9351-7516-48a4-badf-01a8f9b5164e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4169163f-3eac-4dd4-b500-a47e3e6bcd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32d9e301-b3e9-4c52-9f82-1d4e6fa0edd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f3c3c294-d351-402e-b081-ff5cb61ab17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saat ini anda terdaftar sebagai Customer General Trade dengan Jangkauan Produk Consumer Goods</value>
      <webElementGuid>4748f989-462e-4bac-a697-b58a3f3bdadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormEditTemplate&quot;)/div[@class=&quot;form-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;note-editor note-frame panel panel-default&quot;]/div[@class=&quot;note-editing-area&quot;]/div[@class=&quot;note-editable&quot;]</value>
      <webElementGuid>bb6b1d8a-0bf1-4f9b-b746-085ecce8ee23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormEditTemplate']/div/div/div[3]/div/div/div/div[3]/div[2]</value>
      <webElementGuid>169e6b00-f697-46b6-b5b1-83114bff9633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/following::div[18]</value>
      <webElementGuid>8a74f9be-2e82-47dc-995f-880a3f5a829c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset to default'])[1]/following::div[29]</value>
      <webElementGuid>9163e47e-84d3-4e09-8c3e-eec03bf600b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>2cd5d26a-8098-41ea-997c-463dc1402ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Saat ini anda terdaftar sebagai Customer General Trade dengan Jangkauan Produk Consumer Goods' or . = 'Saat ini anda terdaftar sebagai Customer General Trade dengan Jangkauan Produk Consumer Goods')]</value>
      <webElementGuid>4c04f0d5-5b5e-4382-b013-3a0ac40ab08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
