<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ad1a63bf-2e14-46c0-af94-e97290a4377b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fileinput-new.thumbnail > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='FormCreatePrincipal']/div/div/div[5]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>782e2090-0ca1-45c9-b3f4-4989d82e52d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/img-placeholder.png</value>
      <webElementGuid>f7afebb0-bda1-4acd-a4c3-89e23e79755c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormCreatePrincipal&quot;)/div[@class=&quot;form-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;fileinput fileinput-new&quot;]/div[@class=&quot;fileinput-new thumbnail&quot;]/img[1]</value>
      <webElementGuid>ae029034-8784-43bd-a61f-b1f346795ae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormCreatePrincipal']/div/div/div[5]/div/div/div/div/img</value>
      <webElementGuid>cb97eca8-8865-4122-8be4-821abb93caf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>88512370-7967-476e-83c8-a5ef9c035b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/img-placeholder.png']</value>
      <webElementGuid>0710cc4a-f967-4be8-a305-706c06c493ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
