<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start OFF Date_startDate</name>
   <tag></tag>
   <elementGuidId>1d134de2-79b8-46ac-8e1a-e8687ae65bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7300f45b-3c09-4d8e-b57b-b3ee913c8f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>90176eb6-5248-4d76-9431-a663e63460c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-model-start</value>
      <webElementGuid>a18ef4f9-68b6-42a7-ac79-0683ab5d5fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4a9f942-e966-4406-b2ff-683a46bc314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start Date</value>
      <webElementGuid>c9817643-8dc8-4405-a829-4f0189e71f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6bb20084-fb45-4259-96d8-839627ff6acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDate&quot;)</value>
      <webElementGuid>6ce1da55-6ecb-46fe-92c2-6942830ff10b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDate']</value>
      <webElementGuid>19dec070-299e-49e0-8898-b70093bf35cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-set-date']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>8fa76639-fdfa-4645-b22d-8230c0c00354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>adf562fb-c2f3-4bfa-8cfd-62b3a9bd3d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'startDate' and @type = 'text' and @placeholder = 'Start Date']</value>
      <webElementGuid>f6d92d9f-d695-4ce7-84d8-a929f97f6d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
