<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Code_ProductName (1)</name>
   <tag></tag>
   <elementGuidId>fa807083-6850-469e-a7c3-148e1a979127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4b41ba8-67f0-486f-a47e-51e4742f042c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>fb2c1cd4-9edb-4e0c-9b5f-25c6fea2d033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>de78d3eb-d298-47e6-8fc6-00bbb6d11f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui-autocomplete-input</value>
      <webElementGuid>dae3e629-049b-4b13-9239-289465758823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c145633-826c-42dc-b056-ab79c555f2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Use 3 Keywords</value>
      <webElementGuid>49339155-2620-4b97-90de-71675a733f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>860844e2-b9c2-43c3-99d2-cf1052d21d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductName&quot;)</value>
      <webElementGuid>c76f72a7-6215-4f6e-95ee-0804d71079ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductName']</value>
      <webElementGuid>6e738033-8b75-4c83-b255-1ca2d48fdb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormCreateProduct']/div/div/div/div/div/div/input</value>
      <webElementGuid>f0cc6a1b-53b2-4fcc-a151-3d7e6e9f6573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>75a4a443-43e9-437f-b28f-d1fdffad155f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductName' and @name = 'ProductName' and @type = 'text' and @placeholder = 'Use 3 Keywords']</value>
      <webElementGuid>3e6f791f-7922-4387-920b-cb5aa61c2252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
