<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Associated British F  B_dt-checkboxes</name>
   <tag></tag>
   <elementGuidId>29273435-1571-42ea-a7b4-f041b13a976e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3f5bf16-a8c2-4ba1-83a4-fa48dd7623b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f0d8f1f9-925e-461a-9795-b181501a6119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>db678809-d639-408a-af9c-44d7a158747b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6858fe94-9057-4f3f-b87b-5404d4d4f934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>f589af42-975e-491c-8f23-16e5c49cbafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9fbef34-3b15-4f92-a726-f80f2787e0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f6c15893-a2d2-4d4e-b99e-f6addad9b71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>60f8edbf-9899-4e6c-ab8c-e3600e30e818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>463f2864-ddca-43a5-bf8b-f2cbb459781e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>e97e9df1-e7df-4bd5-b21e-7a420451b4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45252026-e1af-4cc6-8496-324e5dee7c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>53d3829c-6bf0-48c1-8e20-5c3685e6dc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>6c34fb02-f6fe-42e1-9486-4dc84f9e09ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e5361939-0851-41a1-ab55-2917577ef7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>8102947a-7ac2-4075-b6b4-2e0f7643b164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>251938bf-f34a-41c5-a7d0-6a1996876f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>99b2d829-0e5d-4c2b-91d5-b904aeb38315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>2303e658-0e11-4e68-ac53-35bd8f59777b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce1ab98d-2cc4-4967-aca1-5c81627ea421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>7b40a0ea-abdb-4549-8982-6305688fbe96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1834d29e-e943-45d1-a560-efa8b50cd3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3d24f77e-e75c-4dce-a15a-41fac2763e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>92125ca3-212f-46e7-9c9c-19b38888179a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cca469e2-d2a5-48a9-8ba5-5f51c0731523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>6c8682ec-2bc4-48de-85ed-c4c2e05a892a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69e438b7-92a9-43f0-9a1f-f9faa56b64e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ef1a5c64-6938-483d-a97b-29d0fa23e402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>551cb041-5159-4ed9-bf02-249ce27cd9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4b05a9a-9116-4f88-b1be-ca66a661bb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>cf192dca-6264-4ea4-9d32-f900f2aeb437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57fec2c5-d171-4020-8a03-7f79e5839e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>523e4edf-aec2-4b86-bfcb-6f36d541b10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>f2dfc859-e0b1-4910-be8f-82b164946033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8dd15f1f-e05c-4295-8bca-9e79be564a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>33fce329-a4ce-466b-bab0-ea51316f1c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61425f28-4ad8-41d4-8f6f-0ebd1dcde426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5f50eb4-f095-4b91-b465-5a44c10a86b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>6b0860b5-5bfa-4a9d-a63c-5beca35cda47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2fcf6d08-a6e8-4b15-b9f7-d4ee1aa006f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableClient&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>7039f11a-3ed8-442b-b8a9-3f8dc64c8368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[5]</value>
      <webElementGuid>3e86b80e-8635-42a2-948f-97b7413c1076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TableClient']/tbody/tr[3]/td/input</value>
      <webElementGuid>9461f8ad-3d29-4b06-9129-07d7beeb827e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>ffae2d9f-5a7e-4d35-98ba-0fd1644bb53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>dec283bf-298f-436d-978d-66eaa055efbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
