<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Set Date_dt-checkboxes</name>
   <tag></tag>
   <elementGuidId>94969d1c-cc4e-433d-baa4-394ca0b9790c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[231]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d76b7fb3-b534-4a68-b1d0-2b4405323424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bab96e9c-addc-40b9-83d1-772b51922e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>09a88712-6c19-485e-8cae-60be363eaf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8906feda-f39a-4752-a579-eaf4cf0a2843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataED&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>d5e729a8-22e3-45df-bbca-716aed88a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd019856-4c05-4ad5-87cf-02d39492ced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>585cde5d-6f6b-483f-a0d5-9fbe562d137c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>7eb7efaa-6999-49be-8d72-91f9acdefdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bf4e020c-b989-44f8-be60-f905e1bf59cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataED&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>edc21eb2-1cf6-4c34-90da-f73a45b6366b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21d576d9-f57f-4da1-9ab8-36604e1dec91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3fa6904-392c-4091-a02e-b597d9600ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-checkboxes</value>
      <webElementGuid>7cc0a094-c690-4eea-8ea9-8cb664f68776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cc3140de-7cc0-48ac-872e-162dbf4cb630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataED&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-checkboxes-cell sorting_1&quot;]/input[@class=&quot;dt-checkboxes&quot;]</value>
      <webElementGuid>3281cbcd-211e-46ef-ad94-a206fdca3195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[231]</value>
      <webElementGuid>ba988d22-69f4-4f29-b1e6-02545c9a5966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='DataED']/tr[13]/td/input</value>
      <webElementGuid>cd163050-7855-4768-b315-3a5b394811b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/table/tbody/tr[13]/td/input</value>
      <webElementGuid>9cd87480-d7ce-4985-aa5e-5e0c1798f031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>46c8d294-e8bb-4f16-bd77-7c6a56fb251e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[223]</value>
      <webElementGuid>a5df9280-3a12-4dda-acee-5cb2dcf800ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='DataED']/tr[5]/td/input</value>
      <webElementGuid>31d27d2c-ceb2-437e-9fc2-96a1282e3100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/table/tbody/tr[5]/td/input</value>
      <webElementGuid>e2bed7a8-c705-4aff-ab54-47acca934f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
