<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DUODERM CGF DRS 20X20CM (1X5PK) NAI</name>
   <tag></tag>
   <elementGuidId>1611f245-07c8-467f-866f-bc425397de31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ui-id-23']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-23</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>58edc8ea-4f4a-44c2-b200-6501473a4adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>56426ce1-a219-430a-b283-1812f77fa722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-23</value>
      <webElementGuid>33d3a50b-270a-4eae-b91a-439ef7e2d4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>35314aba-8a5a-4bf9-ad3d-7b6c146fdc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DUODERM CGF DRS 20X20CM (1X5PK) NAI</value>
      <webElementGuid>c633e146-0133-4588-ab71-16cfee760d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-23&quot;)</value>
      <webElementGuid>f26e4311-5a93-42e2-a741-ad6bfeaa8447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8807269f-6558-4f39-833e-1a276427f7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>b669306d-dfc1-4909-afed-2cc921bf3124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-13</value>
      <webElementGuid>7501ae00-cecd-46aa-9742-cb85c862457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>442d6fa7-7064-4e0a-8e48-5a1691fc0758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DUODERM CGF DRS 20X20CM (1X5PK) NAI</value>
      <webElementGuid>683d5500-45e1-47ab-b31e-5f2c0b4b3d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-13&quot;)</value>
      <webElementGuid>b16845cd-ab4e-4f62-807f-823051263028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-23']</value>
      <webElementGuid>56e0bcd9-cd3c-4743-a295-fdbf54e6c3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[2]</value>
      <webElementGuid>1f07eef5-269d-443d-bb85-48f868bc235b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUODERM CGF DRS 10X10CM (1X5PK) NAI'])[1]/following::li[1]</value>
      <webElementGuid>5b23c4cd-0924-401e-a1aa-f25c5c1a0c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-23', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>4531e304-153a-4d3d-9839-2cd6ddb36d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUODERM XTHIN DRS 10X10CM (1X10PK) NAI'])[1]/preceding::li[1]</value>
      <webElementGuid>16f319a5-e5d5-4e8f-8832-c6875e206d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUODERM XTHIN DRS 5X20CM (1X10PK) NAI'])[1]/preceding::li[2]</value>
      <webElementGuid>ec28aa42-808a-4d45-b0b6-e6a56e9c827d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DUODERM CGF DRS 20X20CM (1X5PK) NAI']/parent::*</value>
      <webElementGuid>451194e4-6feb-4f92-b0de-be4c207ebcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[2]</value>
      <webElementGuid>b69a40db-75e4-49da-aa68-ef338392e36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-23' and (text() = 'DUODERM CGF DRS 20X20CM (1X5PK) NAI' or . = 'DUODERM CGF DRS 20X20CM (1X5PK) NAI')]</value>
      <webElementGuid>b4b830aa-f6a9-4101-897c-20bfb0c90a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-13']</value>
      <webElementGuid>66b88def-de0c-456f-8b7f-ef36340b0c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-13', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>508011d5-e823-4901-a6e4-8fdb5e2f5f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-13' and (text() = 'DUODERM CGF DRS 20X20CM (1X5PK) NAI' or . = 'DUODERM CGF DRS 20X20CM (1X5PK) NAI')]</value>
      <webElementGuid>2417987e-7f94-4837-be8e-1dd00137b907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
