<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DUMMY ELECTRODES COMP(1PC)</name>
   <tag></tag>
   <elementGuidId>89572c66-cb04-49cb-8d93-294f60db1e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ui-id-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d628f7f0-56b3-4e19-995c-54570478ff1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>63eeabb2-46ce-484e-b7f3-4c7e323d663d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-18</value>
      <webElementGuid>55a309b7-8ec7-4ce3-b345-73a773948462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>28dc2a5e-7d24-49e9-96b0-b77941a48081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DUMMY ELECTRODES COMP(1PC)</value>
      <webElementGuid>af66c631-e4b2-43a0-9716-979fee39c808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-18&quot;)</value>
      <webElementGuid>48eb52aa-51ae-4a50-90d9-22edae1b864d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-18']</value>
      <webElementGuid>98d641a4-5632-45c6-876b-3e6e4f9d57f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[7]</value>
      <webElementGuid>29b3b93e-fdba-4dcf-a8a2-b6b721b327f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELECTRODE HOLDER MODULE, COMPLETE, 918'])[1]/following::li[1]</value>
      <webElementGuid>70804e01-d4b0-4f32-8bbe-23a8dffeceb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAVRIX ADULT INJ 1440MUI 1X1D FG'])[1]/following::li[2]</value>
      <webElementGuid>cd3036de-8e8d-4574-b9ff-1ee5fea4db55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MICRO ELECTRODE DUMMY'])[1]/preceding::li[1]</value>
      <webElementGuid>f765de1d-ef6a-4bf3-9d9f-876256977d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MSS-DUMMY SENSOR VERSANDFB 221'])[1]/preceding::li[2]</value>
      <webElementGuid>74de89a8-3761-4826-925a-1e96842fa70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DUMMY ELECTRODES COMP(1PC)']/parent::*</value>
      <webElementGuid>3687cc22-64cf-4726-be9b-fdbbf335851f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[7]</value>
      <webElementGuid>4400e47f-18ac-4bd9-9079-71ab64ba4d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-18' and (text() = 'DUMMY ELECTRODES COMP(1PC)' or . = 'DUMMY ELECTRODES COMP(1PC)')]</value>
      <webElementGuid>a6b47318-fd91-4993-9c02-aa14820f6f8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
