<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DUODERM XTHIN DRS 5X20CM (1X10PK) NAI</name>
   <tag></tag>
   <elementGuidId>b9f33e54-5c52-42fe-8088-bd3538931ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ui-id-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>06cd72e4-bd17-4382-8fd7-e2a01d33d835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>36802755-53b2-4a1c-b079-9cd45a5d8db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-5</value>
      <webElementGuid>597d9103-a054-4b37-b4c2-969809a1da52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b2cfc9e1-af5b-4536-8cc3-d5ac7432ec0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DUODERM XTHIN DRS 5X20CM (1X10PK) NAI</value>
      <webElementGuid>fcf6cfad-c308-4519-8467-c00cc0586ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-5&quot;)</value>
      <webElementGuid>f0eb8bf4-9dbf-4148-abe3-f9749e1f35d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-5']</value>
      <webElementGuid>cb01ebc4-e52b-4ccc-bdc9-7d7cc161fa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[4]</value>
      <webElementGuid>e990ee3f-1bfe-407c-b66b-88e48052a61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUODERM XTHIN DRS 10X10CM (1X10PK) NAI'])[1]/following::li[1]</value>
      <webElementGuid>79ef8158-22ea-43e6-a224-01444a0173a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUODERM CGF DRS 20X20CM (1X5PK) NAI'])[1]/following::li[2]</value>
      <webElementGuid>0783878d-8125-4592-92bb-f3545dfe483c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAVRIX ADULT INJ 1440MUI 1X1D FG'])[1]/preceding::li[1]</value>
      <webElementGuid>9e43ee3e-40fa-4dbf-a6fe-1027c4567315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELECTRODE HOLDER MODULE, COMPLETE, 918'])[1]/preceding::li[2]</value>
      <webElementGuid>a546cba0-896e-4ad1-b4a8-ecff8eb37049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DUODERM XTHIN DRS 5X20CM (1X10PK) NAI']/parent::*</value>
      <webElementGuid>70f548b0-6d8d-4b96-992e-9f4cae43748e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[4]</value>
      <webElementGuid>b0e152de-e0cc-4a5f-96db-4b9491b81e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-5' and (text() = 'DUODERM XTHIN DRS 5X20CM (1X10PK) NAI' or . = 'DUODERM XTHIN DRS 5X20CM (1X10PK) NAI')]</value>
      <webElementGuid>8e1ce81a-6fd8-4cee-8aa0-696fa70b24d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
