<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DUODERM CGF DRS 10X10CM (1X5PK) NAI</name>
   <tag></tag>
   <elementGuidId>d417aaeb-956d-453c-ae77-2d1579551e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ui-id-42']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-42</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2b98b0b5-2b4f-43f8-b209-4bcb14dcfc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>5167945e-7944-4b6f-b3b0-c1bcd8a23d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-42</value>
      <webElementGuid>f93c9c4e-c6a7-4ac2-a665-8480ca41306e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5959e7bf-0055-4ca3-80e6-ed6826c2ee19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DUODERM CGF DRS 10X10CM (1X5PK) NAI</value>
      <webElementGuid>e1bc7eb9-d0c2-46e0-88bc-a75b721328a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-42&quot;)</value>
      <webElementGuid>930be48e-3bca-463b-9dfb-feb4b92eb141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-42']</value>
      <webElementGuid>04682dec-9e6d-47f1-a57a-4e4a207a8182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li</value>
      <webElementGuid>90aee15b-dc46-4908-b136-5ba01a291e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-42', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>fbb4e57f-af52-464c-b680-1f47d3a0c532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::li[1]</value>
      <webElementGuid>e7f4d205-6cdb-4a82-8242-1f7ef0de20d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUODERM CGF DRS 20X20CM (1X5PK) NAI'])[1]/preceding::li[1]</value>
      <webElementGuid>09af08df-aeec-4194-91b6-3438b8990f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUODERM XTHIN DRS 10X10CM (1X10PK) NAI'])[1]/preceding::li[2]</value>
      <webElementGuid>dc6b1d1c-f89c-432d-8a31-91b996debec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DUODERM CGF DRS 10X10CM (1X5PK) NAI']/parent::*</value>
      <webElementGuid>ddbf8d63-892f-49d9-aa5c-5dff10323f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li</value>
      <webElementGuid>191d98e7-9623-4d8f-9a13-e706664895d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-42' and (text() = 'DUODERM CGF DRS 10X10CM (1X5PK) NAI' or . = 'DUODERM CGF DRS 10X10CM (1X5PK) NAI')]</value>
      <webElementGuid>0dae1917-d3ed-4ac0-8700-750ccaa0471b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
