<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_NATUR-E 100 5X4 KAPSUL LUNAK PROMO PACK</name>
   <tag></tag>
   <elementGuidId>a2972cb4-f52c-417b-9c90-24ac5b09e290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ui-id-12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6cba58d2-8381-4ffb-ac41-b8c911193a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>4dfd658f-23a9-415d-9d17-b39f28c073e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-12</value>
      <webElementGuid>b5befadc-4fa9-4b49-bede-5f44b44e2a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f86af51f-6050-4ff0-83da-cf404dc715e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NATUR-E 100 5X4 KAPSUL LUNAK PROMO PACK</value>
      <webElementGuid>c6a0e0bd-b553-463b-81e6-908431b90c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-12&quot;)</value>
      <webElementGuid>3ba652d0-0f5b-424b-8197-9d2ec571753d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-12']</value>
      <webElementGuid>75ff7769-22ef-485c-ac4b-95a6a98563cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li</value>
      <webElementGuid>e357c3a0-3a6d-4c71-b330-218f2624caa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-12', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>478b37c1-6d0e-4a5a-b55b-7aa530b8e7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::li[1]</value>
      <webElementGuid>bca76763-3d3f-4f3b-bf1c-b6e2f10faafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NATUR-E 300 5X4 KAPSUL LUNAK PROMO PACK'])[1]/preceding::li[1]</value>
      <webElementGuid>f85bf3d3-1ba9-45fb-9ee3-7c314974afa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NATUR-E ADVANCE 5X4 KAPSUL LUNAK PROMO P'])[1]/preceding::li[2]</value>
      <webElementGuid>43b698ad-afe2-441a-8275-14cfae32f603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NATUR-E 100 5X4 KAPSUL LUNAK PROMO PACK']/parent::*</value>
      <webElementGuid>64c97c52-3d82-47bf-bdf3-e59023b4e901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li</value>
      <webElementGuid>9cdc6f2c-8741-440a-997b-30490778ca56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-12' and (text() = 'NATUR-E 100 5X4 KAPSUL LUNAK PROMO PACK' or . = 'NATUR-E 100 5X4 KAPSUL LUNAK PROMO PACK')]</value>
      <webElementGuid>b3151921-3fd5-4aa7-a4f8-e276819ec3ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
