<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Active                              _94a6d0</name>
   <tag></tag>
   <elementGuidId>0a9c2bd7-531e-42cc-871f-9e441efac151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='isactivePrincipalSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isactivePrincipalSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b06f4f95-1f9c-4121-b327-b8fcc0d3b57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isactiveSearch</value>
      <webElementGuid>87e7d09d-6624-47cf-85b5-8370d5877d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isactivePrincipalSearch</value>
      <webElementGuid>37da5ea5-689c-4f78-a4b4-36d16e829981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5ef5fb6-e609-4ead-80b2-4147574423a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Active
                                            In-Active
                                        </value>
      <webElementGuid>db07517a-7cf4-4b7e-8bcb-90279816742f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isactivePrincipalSearch&quot;)</value>
      <webElementGuid>d9f1d1ca-289b-4eb5-b88e-d554e69891e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='isactivePrincipalSearch']</value>
      <webElementGuid>85a7cae0-9d92-42cd-92d2-4462c0a3206c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchPrincipal']/div/div/div/div/div/select</value>
      <webElementGuid>4352da04-3ca0-4036-9fa1-461ff332fafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>7041a8f3-8ebc-42ce-9c11-560e445d2440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::select[2]</value>
      <webElementGuid>7dbb18fe-89dd-40f0-bec7-ed49bde14073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a322c30a-c080-4f95-892f-79092f0445c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'isactiveSearch' and @id = 'isactivePrincipalSearch' and (text() = '
                                            Active
                                            In-Active
                                        ' or . = '
                                            Active
                                            In-Active
                                        ')]</value>
      <webElementGuid>27a083c3-e9fb-4e77-864b-062579b2d682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
