<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_Description</name>
   <tag></tag>
   <elementGuidId>e94cde26-21e7-4dcb-bccf-77824cd485b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ca93d2d-392e-4a90-8b97-2179069f842a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>54994c43-1e8d-4cf3-9c51-d13bd10e4e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>b4433017-9250-4839-9175-da4e7828e17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>7b37ad79-5e8e-44b8-8668-80d3bfe7e908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)</value>
      <webElementGuid>bd461c73-71bc-4b4b-87fc-302a8d40e2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8f51d94e-ebf6-4d71-aa98-3ac6ce0f538f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6899be45-8f1b-4d7f-973d-e2cbf4e1010f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>29de59e9-b631-44b9-860f-f2b031fa4943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>9a78d2e0-028e-4383-8f00-e96adf482d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)</value>
      <webElementGuid>3f551fc0-fd10-4c38-8f7a-5b1e052ada5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>49bdb943-6940-4187-9b38-03e8be935e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac5cbeda-ad85-461a-a5fd-3a9a6c3e9849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65681fdb-dea8-440e-b8bb-3c0aed429ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Description must be a string or array type with a maximum length of '5000'.</value>
      <webElementGuid>6d33a12c-f534-413e-8e78-18cbcbe80690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>f6206eb8-a145-4efd-9d74-693d35a98dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>137aee78-c49b-4dff-bee6-51b6b024b525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>9a969ac5-be69-48df-82ca-a2e7eb69b99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>6ed6189d-fe8b-4c02-9138-911bd41de42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)</value>
      <webElementGuid>c52bcd72-f151-4e99-931a-400998f99460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>67b4d93a-8e4d-4dd2-af3f-1e9d52b065ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2d730842-ffd6-43d2-abc9-49352a4da6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>944ae022-d700-4ed8-8461-5601e6b774a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Description must be a string or array type with a maximum length of '5000'.</value>
      <webElementGuid>18525e52-c909-452f-a8a5-ec28518e92a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>11807451-151b-47fd-b6bc-8f8100506172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>3317fcbb-2cad-4fdd-9333-357e856b3714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>d22f8733-9832-40fd-adbd-36706ebf9fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>a5a31f42-2457-4594-a50e-269fc49881fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)</value>
      <webElementGuid>56855075-babb-4e8d-8351-cf8c1bc4bb2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Description']</value>
      <webElementGuid>ff248aaf-09f2-4a82-804a-da8f262801a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormCreateTemplateOrder']/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>b82661c4-afa5-42ca-bc42-9332e9bb0681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6fbc8229-e100-4696-8210-4551060ea9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Description' and @name = 'Description']</value>
      <webElementGuid>6769e1fd-89e4-4f28-a083-a03733f3ae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormCreatePrincipal']/div/div/div[3]/div/div/textarea</value>
      <webElementGuid>8dc19cc2-7816-40a0-a122-5acc5f947f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
